name: Codacy Coverage Reporter

on:
  push:
  pull_request:
    branches: [main]

jobs:
  codacy-coverage-reporter:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: codacy-coverage-reporter
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
      - name: Build
        run: go build
      - name: Run unit tests
        run: go test -coverprofile=unit.coverage.out ./...
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: unit.coverage.out
          # coverage-reports: <PATH_TO_REPORT>
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>